// ShootingLocation type: provides autocomplete for common values while allowing any string
export type ShootingLocation =
	| 'Alabama'
	| 'Albuquerque, NM'
	| 'Arkansas'
	| 'Atlanta, GA'
	| 'Austin, TX'
	| 'Australia'
	| 'Belgrade, Serbia'
	| 'Biloxi, MS'
	| 'Boston, MA'
	| 'Bulgaria'
	| 'Calgary, AB'
	| 'Calgary, MB'
	| 'California'
	| 'Central Florida'
	| 'Chicago, IL'
	| 'Chile'
	| 'Cleveland, OH'
	| 'Czech Republic'
	| 'Dallas, TX'
	| 'Denmark'
	| 'Detroit, MI'
	| 'Dominican Republic'
	| 'Edmonton, AB'
	| 'Greenport, NY'
	| 'Halifax, NS'
	| 'Hamilton, ON'
	| 'Hawaii'
	| 'Jordan'
	| 'Las Vegas, NV'
	| 'London, UK'
	| 'Los Angeles, CA'
	| 'Massachusetts'
	| 'Mexico'
	| 'Minneapolis, MN'
	| 'Minnesota'
	| 'Montana'
	| 'Montana and Utah'
	| 'Montreal'
	| 'Montreal, QC'
	| 'Nashville, TN'
	| 'Nevada'
	| 'New Mexico'
	| 'New Orleans, LA'
	| 'New York, NY'
	| 'New Zealand'
	| 'Newport, RI'
	| 'Nova Scotia'
	| 'Oklahoma'
	| 'Orlando, FL'
	| 'Ottawa, ON'
	| 'Palm Springs, CA'
	| 'Paris, France'
	| 'Philadelphia, PA'
	| 'Pittsburgh, PA'
	| 'Portland, Maine'
	| 'Portland, Oregon'
	| 'Puerto Rico'
	| 'Santa Fe, NM'
	| 'Savannah, GA'
	| 'South Africa'
	| 'South Carolina'
	| 'Spain'
	| 'Spetses, Greece'
	| 'Syracuse, NY'
	| 'TBA'
	| 'TBD'
	| 'Tampa, FL'
	| 'Tokyo'
	| 'Toronto, ON'
	| 'United Kingdom'
	| 'Vancouver, BC'
	| 'Various'
	| 'Venice, Italy'
	| 'Victoria, BC'
	| 'Virginia'
	| 'Washington, DC'
	| 'Wilmington, NC'
	| 'Winnipeg, MB'
	| (string & {}); // Allows any other string while preserving autocomplete
